# Site settings
title: Programming in JavaScript
author: Tom Shen
email: tomshen@cmu.edu
description: >
  A tutorial teaching the basics of programming in JavaScript. Created for Eddy
  Man Kim's Design Communication course at CMU.
baseurl: "/learnjs" # the subpath of your site, e.g. /blog/
url: "http://www.tomshen.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
